language: python
install:
  - pip install -r requirements/ci.txt
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=manifest
script:
  - tox
after_success:
  - codecov
sudo: false
notifications:
  slack:
    secure:
