language: python
python: 3.5
install:
  - pip install -r requirements/ci.pip
env:
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=manifest
script:
  - tox
after_success:
  - codecov
sudo: false
notifications:
  slack:
    secure:
